apiVersion: apps/v1
kind: Deployment
metadata:
  name: battleships-deployment
spec:
  replicas: 2  # Adjust the number of replicas as needed
  selector:
    matchLabels:
      app: battleships
  template:
    metadata:
      labels:
        app: battleships
    spec:
      containers:
        - name: battleships-container
          image: rameshkumarverma/battleships-app:latest  # Replace with your Docker image details
          ports:
            - containerPort: 80
          env:
            - name: NODE_ENV
              value: production
