apiVersion: v1
kind: Service
metadata:
  name: dailyjournal-service
spec:
  selector:
    app: dailyjournal
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer  # Change to NodePort or ClusterIP based on your needs
