name: Matrix Echo Workflow

on: [push]

jobs:
  echo-job:
    timeout-minutes: 15
    runs-on: warpdev-ubuntu-latest-amd64-4x
    strategy:
      fail-fast: false
      matrix:
        node-version: [20.x]
        shard:
          [
            1,
            2,
            3,
            4,
            5,
            6,
            7,
            8,
            9,
            10,
            11,
            12,
            13,
            14,
            15,
            16,
            17,
            18,
            19,
            20,
            21,
            22,
            23,
            24,
            25,
            26,
            27,
            28,
            29,
            30,
            31,
            32,
            33,
            34,
            35,
            36,
            37,
            38,
            39,
            40,
            41,
            42,
            43,
            44,
            45,
            46,
            47,
            48,
            49,
            50,
            51,
            52,
            53,
            54,
            55,
            56,
            57,
            58,
            59,
            60,
          ]

    env:
      NODE_OPTIONS: "--max-old-space-size=14336"

    steps:
      - name: Echo Hello World
        run: echo Hello World
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm install --frozen-lockfile --prefer-offline
